---
language: ruby
rvm:
  - 1.9.3
  - jruby-19mode
  - rbx-2
  - 2.1.5
gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
matrix:
  # fast_finish: true
  allow_failures:
    - rvm: jruby-19mode
    - rvm: rbx-2